/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'

const DocsServerStackLazyRouteImport = createFileRoute('/docs/server-stack')()
const DocsServerRackLazyRouteImport = createFileRoute('/docs/server-rack')()

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsServerStackLazyRoute = DocsServerStackLazyRouteImport.update({
  id: '/server-stack',
  path: '/server-stack',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/server-stack.lazy').then((d) => d.Route),
)
const DocsServerRackLazyRoute = DocsServerRackLazyRouteImport.update({
  id: '/server-rack',
  path: '/server-rack',
  getParentRoute: () => DocsRouteRoute,
} as any).lazy(() =>
  import('./routes/docs/server-rack.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/server-rack': typeof DocsServerRackLazyRoute
  '/docs/server-stack': typeof DocsServerStackLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/docs/server-rack' | '/docs/server-stack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/docs/server-rack' | '/docs/server-stack'
  id: '__root__' | '/' | '/docs' | '/docs/server-rack' | '/docs/server-stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/server-stack': {
      id: '/docs/server-stack'
      path: '/server-stack'
      fullPath: '/docs/server-stack'
      preLoaderRoute: typeof DocsServerStackLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/server-rack': {
      id: '/docs/server-rack'
      path: '/server-rack'
      fullPath: '/docs/server-rack'
      preLoaderRoute: typeof DocsServerRackLazyRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsServerRackLazyRoute: typeof DocsServerRackLazyRoute
  DocsServerStackLazyRoute: typeof DocsServerStackLazyRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsServerRackLazyRoute: DocsServerRackLazyRoute,
  DocsServerStackLazyRoute: DocsServerStackLazyRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
